### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_retinanet.lib.nms._ext.nms._nms'

### ISSUE THREAD

**Issue by wangzt2012** [tatigabru/kaggle-rsna#2]
I try to import pytorch_retinanet.model, which is in src/train_runner.py, then the error is like this:

Traceback (most recent call last):
  File "src/train_runner.py", line 20, in <module>
    import pytorch_retinanet.model
  File "/home/xxx/project/chestDR/pneumonia/kaggle-rsna/src/pytorch_retinanet/model.py", line 10, in <module>
    from .lib.nms.pth_nms import pth_nms
  File "/home/xxx/project/chestDR/pneumonia/kaggle-rsna/src/pytorch_retinanet/lib/nms/pth_nms.py", line 2, in <module>
    from ._ext import nms
  File "/home/xxx/project/chestDR/pneumonia/kaggle-rsna/src/pytorch_retinanet/lib/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'pytorch_retinanet.lib.nms._ext.nms._nms'

**Comment by v-raagini** [comment]
Hi, 
Did you find a solution to this?

**Comment by alxndrkalinin** [comment]
@raagini99 depending on PyTorch version, you may have to [compile NMS extension manually](https://github.com/yhenon/pytorch-retinanet/tree/71f8e0a8215ebc4c54d9ad2762d47b4ec6738d32#installation)

**Comment by v-raagini** [comment]
Thanks. Will try doing that
