### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_retinanet.lib.nms._ext.nms._nms'

### ISSUE THREAD

**Issue by Jeff-Zhouxiaolong** [tatigabru/kaggle-rsna#5]
Dear friends:
         when I running the train_runner.py file, I get a mistake: ModuleNotFoundError: No module named 'pytorch_retinanet.lib.nms._ext.nms._nms'
`Traceback (most recent call last):
  File "D:/chloe/Project/kaggle-rsna/src/train_runner.py", line 20, in <module>
    import pytorch_retinanet.model
  File "D:\chloe\Project\kaggle-rsna\src\pytorch_retinanet\model.py", line 10, in <module>
    from .lib.nms.pth_nms import pth_nms
  File "D:\chloe\Project\kaggle-rsna\src\pytorch_retinanet\lib\nms\pth_nms.py", line 2, in <module>
    from ._ext import nms
  File "D:\chloe\Project\kaggle-rsna\src\pytorch_retinanet\lib\nms\_ext\nms\__init__.py", line 5, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'pytorch_retinanet.lib.nms._ext.nms._nms'`

How can I solve it，  thank you

**Comment by tatigabru** [comment]
You need to install retinanet first. Unfortunately, over time it got old, so you need older version of PyTorch to do so

**Comment by alxndrkalinin** [comment]
See [this issue](https://github.com/tatigabru/kaggle-rsna/issues/2#issuecomment-653733005)
